[book]
authors = ["Dada Contributors"]
language = "en"
src = "src"
title = "Dada Language Specification"

[preprocessor.dada-mdbook-preprocessor]
command = "cargo run --bin dada-mdbook-preprocessor --"

[output.html]
site-url = "/spec/"
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/dada-lang/dada"
git-repository-icon = "fab-github"